spring.application.name=URL-Shortener
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=3105
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# Server Configuration
# ==============================

server.port=8080


# ==============================
# Redis Configuration
# ==============================

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0


# ==============================
# URL Shortener Configuration
# ==============================

urlshortener.base-url=http://localhost:8080

urlshortener.short-code.length=6
urlshortener.short-code.max-attempts=10

urlshortener.rate-limit.requests-per-minute=2
urlshortener.rate-limit.requests-per-hour=10

urlshortener.cache.ttl-minutes=30

urlshortener.cleanup.interval-minutes=5
urlshortener.cleanup.expired-urls-batch-size=100


# ==============================
# Logging Configuration
# ==============================

logging.level.com.shahbytes.tinylink=DEBUG
logging.level.org.springframework.data.redis=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n