package com.demo.service;

import com.demo.dto.CreateUrlRequest;
import com.demo.dto.UrlResponse;
import com.demo.dto.UrlStatsResponse;
import com.demo.entity.Url;
import com.demo.exception.DuplicateAliasException;
import com.demo.exception.InvalidUrlException;
import com.demo.exception.UrlExpiredException;
import com.demo.exception.UrlNotFoundException;
import com.demo.repository.UrlRepository;
import com.demo.util.ShortCodeGenerator;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.LocalDateTime;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UrlShortenerServiceTest {

    @Mock
    private UrlRepository urlRepository;

    @Mock
    private CacheService cacheService;

    @Mock
    private ShortCodeGenerator shortCodeGenerator;

    @InjectMocks
    private UrlShortenerService urlShortenerService;

    @BeforeEach
    void setUp() {
        ReflectionTestUtils.setField(urlShortenerService, "baseUrl", "http://localhost:8080");
        ReflectionTestUtils.setField(urlShortenerService, "shortCodeLength", 6);
        ReflectionTestUtils.setField(urlShortenerService, "maxAttempts", 10);
        ReflectionTestUtils.setField(urlShortenerService, "defaultCacheTtlMinutes", 60L);
    }

    @Test
    @DisplayName("Should successfully create a short URL with auto-generated code")
    void testCreateShortUrlAutoGenerated() {
        CreateUrlRequest request = CreateUrlRequest.builder()
                .originalUrl("https://example.com/test-page")
                .build();

        when(shortCodeGenerator.generateShortCode(6)).thenReturn("aB92xK");
        when(urlRepository.existsByShortCode("aB92xK")).thenReturn(false);

        Url savedUrl = Url.builder()
                .id(1L)
                .originalUrl("https://example.com/test-page")
                .shortCode("aB92xK")
                .createdAt(LocalDateTime.now())
                .clickCount(0)
                .build();

        when(urlRepository.save(any(Url.class))).thenReturn(savedUrl);

        UrlResponse response = urlShortenerService.createShortUrl(request);

        assertNotNull(response);
        assertEquals("aB92xK", response.getShortCode());
        assertEquals("http://localhost:8080/aB92xK", response.getShortUrl());
        assertEquals("https://example.com/test-page", response.getOriginalUrl());

        verify(cacheService).saveUrl(eq("aB92xK"), eq("https://example.com/test-page"), anyLong());
    }

    @Test
    @DisplayName("Should successfully create a short URL with custom alias")
    void testCreateShortUrlCustomAlias() {
        CreateUrlRequest request = CreateUrlRequest.builder()
                .originalUrl("https://example.com/custom")
                .customAlias("my-link")
                .build();

        when(urlRepository.existsByShortCode("my-link")).thenReturn(false);

        Url savedUrl = Url.builder()
                .id(2L)
                .originalUrl("https://example.com/custom")
                .shortCode("my-link")
                .createdAt(LocalDateTime.now())
                .clickCount(0)
                .build();

        when(urlRepository.save(any(Url.class))).thenReturn(savedUrl);

        UrlResponse response = urlShortenerService.createShortUrl(request);

        assertEquals("my-link", response.getShortCode());
        assertEquals("http://localhost:8080/my-link", response.getShortUrl());
    }

    @Test
    @DisplayName("Should throw DuplicateAliasException when custom alias is taken")
    void testCreateShortUrlDuplicateAlias() {
        CreateUrlRequest request = CreateUrlRequest.builder()
                .originalUrl("https://example.com/dup")
                .customAlias("existing-alias")
                .build();

        when(urlRepository.existsByShortCode("existing-alias")).thenReturn(true);

        assertThrows(DuplicateAliasException.class, () -> urlShortenerService.createShortUrl(request));
    }

    @Test
    @DisplayName("Should throw InvalidUrlException for malformed URLs")
    void testCreateShortUrlInvalid() {
        CreateUrlRequest request = CreateUrlRequest.builder()
                .originalUrl("not-a-valid-url")
                .build();

        assertThrows(InvalidUrlException.class, () -> urlShortenerService.createShortUrl(request));
    }

    @Test
    @DisplayName("Should redirect using Redis cache HIT")
    void testGetOriginalUrlAndRedirectCacheHit() {
        when(cacheService.getUrl("aB92xK")).thenReturn(Optional.of("https://example.com/test-page"));

        String originalUrl = urlShortenerService.getOriginalUrlAndRedirect("aB92xK");

        assertEquals("https://example.com/test-page", originalUrl);
        verify(urlRepository).incrementClickCount("aB92xK");
        verify(urlRepository, never()).findByShortCode(anyString());
    }

    @Test
    @DisplayName("Should redirect using MySQL DB on Redis cache MISS")
    void testGetOriginalUrlAndRedirectCacheMiss() {
        when(cacheService.getUrl("aB92xK")).thenReturn(Optional.empty());

        Url dbUrl = Url.builder()
                .id(1L)
                .originalUrl("https://example.com/test-page")
                .shortCode("aB92xK")
                .createdAt(LocalDateTime.now())
                .clickCount(5)
                .build();

        when(urlRepository.findByShortCode("aB92xK")).thenReturn(Optional.of(dbUrl));

        String originalUrl = urlShortenerService.getOriginalUrlAndRedirect("aB92xK");

        assertEquals("https://example.com/test-page", originalUrl);
        verify(urlRepository).incrementClickCount("aB92xK");
        verify(cacheService).saveUrl(eq("aB92xK"), eq("https://example.com/test-page"), anyLong());
    }

    @Test
    @DisplayName("Should throw UrlNotFoundException when shortCode does not exist")
    void testGetOriginalUrlNotFound() {
        when(cacheService.getUrl("unknown")).thenReturn(Optional.empty());
        when(urlRepository.findByShortCode("unknown")).thenReturn(Optional.empty());

        assertThrows(UrlNotFoundException.class, () -> urlShortenerService.getOriginalUrlAndRedirect("unknown"));
    }

    @Test
    @DisplayName("Should throw UrlExpiredException when URL has passed expiration date")
    void testGetOriginalUrlExpired() {
        when(cacheService.getUrl("expired123")).thenReturn(Optional.empty());

        Url expiredUrl = Url.builder()
                .id(3L)
                .originalUrl("https://example.com/expired")
                .shortCode("expired123")
                .createdAt(LocalDateTime.now().minusHours(2))
                .expiresAt(LocalDateTime.now().minusHours(1))
                .clickCount(10)
                .build();

        when(urlRepository.findByShortCode("expired123")).thenReturn(Optional.of(expiredUrl));

        assertThrows(UrlExpiredException.class, () -> urlShortenerService.getOriginalUrlAndRedirect("expired123"));
        verify(cacheService).deleteUrl("expired123");
    }

    @Test
    @DisplayName("Should return URL stats correctly")
    void testGetUrlStats() {
        Url dbUrl = Url.builder()
                .id(1L)
                .originalUrl("https://example.com/stats")
                .shortCode("stat123")
                .createdAt(LocalDateTime.now())
                .clickCount(42)
                .build();

        when(urlRepository.findByShortCode("stat123")).thenReturn(Optional.of(dbUrl));

        UrlStatsResponse stats = urlShortenerService.getUrlStats("stat123");

        assertNotNull(stats);
        assertEquals("stat123", stats.getShortCode());
        assertEquals(42, stats.getClickCount());
        assertEquals("https://example.com/stats", stats.getOriginalUrl());
    }

    @Test
    @DisplayName("Should delete URL from MySQL and Redis")
    void testDeleteUrl() {
        Url dbUrl = Url.builder()
                .id(1L)
                .shortCode("del123")
                .originalUrl("https://example.com/del")
                .build();

        when(urlRepository.findByShortCode("del123")).thenReturn(Optional.of(dbUrl));

        urlShortenerService.deleteUrl("del123");

        verify(urlRepository).delete(dbUrl);
        verify(cacheService).deleteUrl("del123");
    }
}
